#!/bin/bash
CONFIG_DIR="$HOME/.config/engine-stressor"
CONSTANTS_FILE="$CONFIG_DIR/constants"

if [ ! -f "$CONSTANTS_FILE" ]; then
  echo "Error: File $CONSTANTS_FILE does not exist."
  exit 1
fi

source "$CONSTANTS_FILE"
source "$SHARE_DIR/system"
source "$SHARE_DIR/rpm"
source "$SHARE_DIR/date"

# network and volume definition to be used in remove and creation
NETNAME="my_network"
VOLNAME="my_volume"
SELINUX_STATUS="ENFORCING"

# just to make sure our example will work
cleanenv() {
    echo -e "INFO: Cleaning any file from previous tests..."
    sudo podman volume rm "${VOLNAME}" --force &> /dev/null
    sudo podman network rm "${NETNAME}" --force &> /dev/null
}

# calling the function
cleanenv

# executing the program in previous dir
pushd ../../../ 1> /dev/null || exit 1

echo -e "INFO: Executing test: SELinux must be [$SELINUX_STATUS]"

echo -e "INFO:"
echo -e "INFO: This test was executed in the following criteria:"
echo -e "INFO:"
echo -e "INFO: Date:" $(current_date)
echo -e "INFO: System information:"
echo -e "INFO: \t - $(system_info)"
echo -e "INFO:"
echo -e "INFO: RPM(s):"
echo -e "INFO: \t - $(rpm_package_version "selinux-policy")"
echo -e "INFO: \t - $(rpm_package_version "libselinux")"
echo -e "INFO:"

    sudo CLEANUP=false \
         VERBOSE=false \
         NETWORK_NAME="${NETNAME}" \
         VOLUME_NAME="${VOLNAME}" \
         IMAGE_COMMAND="sleep 3600" \
         IMAGE_NAME_CONTAINER="quay.io/centos-sig-automotive/automotive-osbuild" \
         NUMBER_OF_CONTAINERS="1" \
         SELINUX_STATUS_MUST_BE="$SELINUX_STATUS" \
         ./engine-stressor

popd 1> /dev/null || exit 1
