#!/bin/bash
# shellcheck disable=SC1091,SC2155,SC2086
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
CONFIG_DIR="$HOME/.config/engine-stressor"
CONSTANTS_FILE="$CONFIG_DIR/constants"

if [ ! -f "$CONSTANTS_FILE" ]; then
  echo "Error: File $CONSTANTS_FILE does not exist."
  exit 1
fi

source "$CONSTANTS_FILE"

on_error() {
    echo -e "FAIL: An error occurred. Exiting..."
    if [[ "${CLEANUP}" = "${FEATURE_ENABLED}" ]]; then
        if [[ "${VERBOSE}" = "${FEATURE_ENABLED}" ]]; then
            echo -e "INFO: Removing total number of containers: ${NUMBER_OF_CONTAINERS}..."
        fi
        ./engine-operations --cleanup-cont

        if [[ "${VERBOSE}" = "${FEATURE_ENABLED}" ]]; then
            echo -e "INFO: Removing network ${NETWORK_NAME}..."
        fi
        ./engine-operations --cleanup-net

        if [[ "${VERBOSE}" = "${FEATURE_ENABLED}" ]]; then
            echo -e "INFO: Removing volume ${VOLUME_NAME}..."
        fi
        ./engine-operations --cleanup-vol
        cgroup_remove
    fi
    exit 1
}

# Set trap to catch errors and call on_error
trap 'on_error' ERR
