#!/bin/bash

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Function to start a new container with the memory exhaustion script
exec_into_container() {
    container_name=$1
    shift
    command=$@
    sudo podman exec "$container_name" /bin/sh -c "$command"
}

# Function to modify the Fedora repository files inside the container
# We are getting 404 errors in Fedora aarch64, let's try this workaround
modify_repo_files() {
    local container_name="$1"
    arch=$(uname -m)

    echo "Modifying the repository settings in the container: $container_name"
    podman exec "$container_name" bash -c "
        repos=('fedora.repo' 'fedora-updates.repo')

        for repo_file in \"\${repos[@]}\"; do
            full_path=\"/etc/yum.repos.d/\$repo_file\"

            if [ -f \$full_path ]; then
                echo '--- BEFORE modification: \$full_path ---'
                cat \$full_path

                echo 'Updating repository file: \$full_path'
                sed -i 's|^metalink=|#metalink=|g' \$full_path

                if [[ \$repo_file == 'fedora.repo' ]]; then
                    sed -i '/^#metalink=/a baseurl=http://download-ib01.fedoraproject.org/pub/fedora/linux/releases/\$releasever/Everything/$arch/os/' \$full_path
                elif [[ \$repo_file == 'fedora-updates.repo' ]]; then
                    sed -i '/^#metalink=/a baseurl=https://download-ib01.fedoraproject.org/pub/fedora/linux/updates/\$releasever/Everything/$arch/' \$full_path
                fi

                echo '--- AFTER modification: \$full_path ---'
                cat \$full_path
            else
                echo 'Repository file not found: \$full_path'
            fi
        done
    "
}

start_initial_container() {

    echo "========== DEBUG: /etc/os-release =================="
    # Debug: Display the contents of /etc/os-release
    sudo cat /etc/os-release
    echo "========== DEBUG: /etc/os-release =================="

    echo "========== DEBUG: /etc/os-release =================="
    # Debug: Display the contents of /etc/yum.repos.d/
    sudo ls /etc/yum.repos.d/
    echo "========== DEBUG: /etc/os-release =================="

    # Read OS information from /etc/os-release
    source /etc/os-release

    # Check if the OS is CentOS or RHEL and the version is 9 or higher
    if [[ "$ID" =~ ^(rhel|centos)$ && "${VERSION_ID%%.*}" -ge 9 ]]; then
        echo "INFO: RHEL or CentOS 9 or higher detected. Creating necessary directories for volume mounts..."
        sudo mkdir -p /var/tmp/varlog /var/tmp/dnf-cache /var/tmp/dnf-lib /var/tmp/rpm

        VOLUME_OPTS="--volume /var/tmp/varlog:/var/log:Z \
                     --volume /var/tmp/dnf-cache:/var/cache/dnf:Z \
                     --volume /var/tmp/dnf-lib:/var/lib/dnf:Z \
                     --volume /var/tmp/rpm:/var/lib/rpm:Z"
    else
        echo "INFO: OS is not RHEL or CentOS 9 or higher. Skipping volume mounts."
        VOLUME_OPTS=""
    fi

    echo "INFO: Starting initial container $MEMORY_EXHAUSTION_BASE_CONTAINER_NAME"
    sudo podman run -d --privileged \
        --name "$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME" \
        --replace \
        --memory="$MEMORY_EXHAUSTION_BASE_CONTAINER_MEMORY_LIMIT" \
        $VOLUME_OPTS \
        -e MEMORY_EXHAUSTION_BASE_CONTAINER_NAME="$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME" \
        -e MEMORY_EXHAUSTION_BASE_CONTAINER_MEMORY_LIMIT="$MEMORY_EXHAUSTION_BASE_CONTAINER_MEMORY_LIMIT" \
        -e IMAGE_NAME_CONTAINER="$IMAGE_NAME_CONTAINER" \
        -e MEMORY_EXHAUSTION_BASE_CONTAINER_STRESS_NG_TIMEOUT="$MEMORY_EXHAUSTION_BASE_CONTAINER_STRESS_NG_TIMEOUT" \
        -e MEMORY_EXHAUSTION_BASE_CONTAINER_THRESHOLD_PERCENT="$MEMORY_EXHAUSTION_BASE_CONTAINER_THRESHOLD_PERCENT" \
        -e MEMORY_EXHAUSTION_BASE_CONTAINER_STRESS_NG_VM="$MEMORY_EXHAUSTION_BASE_CONTAINER_STRESS_NG_VM" \
        -e MEMORY_EXHAUSTION_BASE_CONTAINER_STRESS_NG_VM_METHOD="$MEMORY_EXHAUSTION_BASE_CONTAINER_STRESS_NG_VM_METHOD" \
        "$IMAGE_NAME_CONTAINER" sleep infinity

    if [ $? -ne 0 ]; then
        echo "ERROR: Failed to start the initial container."
        return 1
    fi

    echo "INFO: Waiting for the container to be fully started..."
    for i in {1..10}; do
        if sudo podman ps --filter "name=$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME" --filter "status=running" | grep -q "$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME"; then
            echo "INFO: Container $MEMORY_EXHAUSTION_BASE_CONTAINER_NAME is running."
            break
        fi
        echo "INFO: Waiting for container to start... ($i/10)"
        sleep 1
    done

    if ! sudo podman ps --filter "name=$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME" --filter "status=running" | grep -q "$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME"; then
        echo "ERROR: Container did not start in time."
        return 1
    fi

    exec_into_container "$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME" "cat /etc/os-release"
    exec_into_container "$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME" "ls /etc/yum.repos.d/"

    # Replace mirror for aarch64 as it's failing - workaround
    modify_repo_files "$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME"

    echo "INFO: Installing dependencies in the container"
    exec_into_container "$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME" "dnf install -y git make which stress-ng procps-ng"

    echo "INFO: Cloning the engine-stressor repository"
    exec_into_container "$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME" "git clone https://github.com/containers/engine-stressor.git"

    echo "INFO: Running the stressor script"
    exec_into_container "$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME" "cd engine-stressor && sudo make install && exhaustion-memory-engine-stressor"
}

# Function to get memory usage of a container as a percentage
# Arguments:
#   container_name: The name of the container
get_memory_usage() {
    local container_name=$1
    podman stats \
        --no-stream \
	--format "{{.MemPerc}}" \
	"$container_name" | sed 's/%//'
}

# Function to create additional containers inside the initial container
# Arguments:
#   container_name: The name of the initial container
create_additional_containers() {
    local container_name=$1
    echo "INFO: Creating additional containers inside $container_name"
    for i in $(seq 1 "$NUMBER_OF_CONTAINERS"); do
        local additional_container_name="${container_name}_nested_$i"
        local run_cmd="podman run -d --name \"$additional_container_name\" --privileged $IMAGE_NAME_CONTAINER sleep infinity"
        echo "INFO: Running nested container $additional_container_name inside $container_name with image $IMAGE_NAME_CONTAINER"
        echo "INFO: $run_cmd"
        if ! sudo podman exec "$container_name" sh -c "$run_cmd"; then
            echo "ERROR: Failed to run nested container $additional_container_name inside $container_name"
            handle_error
        fi
        echo "INFO: Started nested container $additional_container_name inside $container_name"
    done
}

# Function to stop and remove the nested containers
cleanup_nested_containers() {
    echo "INFO: Cleaning up nested containers"
    for i in $(seq 1 $NUMBER_OF_CONTAINERS); do
        local additional_container_name="${MEMORY_EXHAUSTION_BASE_CONTAINER_NAME}_nested_$i"
        if podman exec "$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME" podman stop "$additional_container_name" && podman exec "$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME" podman rm "$additional_container_name" --force; then
            echo "INFO: Nested container $additional_container_name stopped and removed successfully"
        else
            echo "ERROR: Failed to stop and remove nested container $additional_container_name"
            exit 1
        fi
    done
}

# Function to stop and remove the initial container
cleanup_initial_container() {
    echo "INFO: Cleaning up container $MEMORY_EXHAUSTION_BASE_CONTAINER_NAME"

    STOP_CONTAINER_CMD="podman stop \"$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME\""
    REMOVE_CONTAINER_CMD="podman rm \"$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME\" --force"

    if eval "$STOP_CONTAINER_CMD"; then
        echo "INFO: Container $MEMORY_EXHAUSTION_BASE_CONTAINER_NAME stopped successfully"
    else
        echo "ERROR: Failed to stop container $MEMORY_EXHAUSTION_BASE_CONTAINER_NAME"
        exit 1
    fi

    if eval "$REMOVE_CONTAINER_CMD"; then
        echo "INFO: Container $MEMORY_EXHAUSTION_BASE_CONTAINER_NAME removed successfully"
    else
        echo "ERROR: Failed to remove container $MEMORY_EXHAUSTION_BASE_CONTAINER_NAME"
        exit 1
    fi
}

# Function to cleanup everything and exit with an error code
handle_error() {
    cleanup_nested_containers
    cleanup_initial_container
    exit 1
}

memory_exhaustion_test() {
    # Constants
    local TIMEOUT=1500  # 25 minutes in seconds

    # Start the initial container
    start_initial_container &

    # Main monitoring loop
    SECONDS=0
    while [ $SECONDS -lt $TIMEOUT ]; do
        # Get the list of current containers and count them
        container_list=$(podman ps --format "{{.Names}}" 2>/dev/null)
        container_count=$(echo "$container_list" | wc -l)

        # Check if the container list is empty
        if [ -z "$container_list" ]; then
            echo "INFO: List of current containers: (0)"
        else
            echo "INFO: List of current containers: ($container_count) $container_list"
        fi

        # Get current memory usage of the initial container
        current_usage=$(get_memory_usage "$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME" 2>/dev/null)

        # Check if current_usage is empty or nothing returned
        if [ -z "$current_usage" ]; then
            echo "INFO: No memory usage data returned for $MEMORY_EXHAUSTION_BASE_CONTAINER_NAME. Continuing to sleep."
            sleep 1
            continue
        fi

        echo "INFO: Current memory usage of $MEMORY_EXHAUSTION_BASE_CONTAINER_NAME: $current_usage%"

        # Check if memory usage exceeds threshold
        if [ "$(echo "$current_usage >= $MEMORY_EXHAUSTION_BASE_CONTAINER_THRESHOLD_PERCENT" | bc)" -eq 1 ]; then
            echo "INFO: Memory usage of $MEMORY_EXHAUSTION_BASE_CONTAINER_NAME exceeded threshold of $MEMORY_EXHAUSTION_BASE_CONTAINER_THRESHOLD_PERCENT%"
            if create_additional_containers "$MEMORY_EXHAUSTION_BASE_CONTAINER_NAME"; then
                echo "INFO: All nested containers started successfully"
                sleep ${MEMORY_EXHAUSTION_BASE_CONTAINER_WAIT_TIME_BEFORE_STOPPING_NESTED_CONTAINERS_IN_SEC}
                cleanup_nested_containers
                cleanup_initial_container
                echo "PASS: Memory exhaustion test completed successfully"
                exit 0
            else
                echo "ERROR: Failed to start nested containers"
                handle_error
            fi
        fi

        # Sleep for a short period before checking memory usage again
        sleep 1
    done

    # If the timeout is reached
    echo "INFO: Memory exhaustion test timed out after 25 minutes."
    cleanup_initial_container
    echo "FAIL: Memory exhaustion test did not complete within the timeout period"
    exit 1
}

# example of usage
# memory_exhaustion_test "memory-exhaustion-test"
