#!/bin/bash -e
# shellcheck disable=SC1091
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
CONFIG_DIR="$HOME/.config/engine-stressor"
CONSTANTS_FILE="$CONFIG_DIR/constants"

if [ ! -f "$CONSTANTS_FILE" ]; then
  echo "Error: File $CONSTANTS_FILE does not exist."
  exit 1
fi

source "$CONSTANTS_FILE"

echo -e "======================"
echo -e "engine-stressor demo"
echo -e "======================\n"

echo -e "[ ${BLUE}INFO${NC} ] removing podman resources from the demo..."

pushd .. 1> /dev/null || exit 1

    echo -e "[ ${BLUE}INFO${NC} ] removing podman volume used during the demo.."
    sudo VOLUME_NAME="my_volume" \
        ./engine-operations \
	    --cleanup-vol &> /dev/null

    echo -e "[ ${BLUE}INFO${NC} ] removing podman network used during the demo.."
    sudo NETWORK_NAME="my_network" \
        ./engine-operations \
	    --cleanup-net &> /dev/null

    echo -e "[ ${BLUE}INFO${NC} ] removing podman containers used during the demo.."
    sudo NUMBER_OF_CONTAINERS="3" ./engine-operations \
        --cleanup-cont &> /dev/null

popd 1> /dev/null || exit 1
