#!/bin/bash
# shellcheck disable=SC1091
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
CONFIG_DIR="$HOME/.config/engine-stressor"
CONSTANTS_FILE="$CONFIG_DIR/constants"

if [ ! -f "$CONSTANTS_FILE" ]; then
  echo "Error: File $CONSTANTS_FILE does not exist."
  exit 1
fi

source "$CONSTANTS_FILE"

podman_ps_by_name() {
    echo -e "\nContainers running listed by name:"
    sudo podman ps --format "\t - {{.Names}}"
}

# network and volume definition to be used in remove and creation
NETNAME="my_network"
VOLNAME="my_volume"
NRM_CONTAINERS=5

echo -e "======================"
echo -e "engine-stressor demo"
echo -e "======================\n"

# Just make sure we are in a fresh env
echo -e "INFO: Cleaning previous engine-stressor container volume settings..."
sudo podman volume rm "${VOLNAME}" --force &> /dev/null

echo -e "INFO: Cleaning previous engine-stressor container network settings..."
sudo podman network rm "${NETNAME}" --force &> /dev/null

echo -e "INFO: Triggering ${NRM_CONTAINERS} containers with engine-stressor..."
pushd .. 1> /dev/null || exit 1
    # starting the engine-stressor
    sudo TOTAL_MEMORY_FOR_THE_NAMESPACE="1G" \
         LIST_CURRENT_STATE=true \
         VERBOSE=true \
	 MEMORY_EXHAUSTION=true \
         MEMORY_EXHAUSTION_BASE_CONTAINER_NAME="memory_eater_base_container" \
         MEMORY_EXHAUSTION_BASE_CONTAINER_MEMORY_LIMIT=512m \
         MEMORY_EXHAUSTION_BASE_CONTAINER_THRESHOLD_PERCENT=90 \
         MEMORY_EXHAUSTION_BASE_CONTAINER_WAIT_TIME_BEFORE_STOPPING_NESTED_CONTAINERS_IN_SEC=5 \
         MEMORY_EXHAUSTION_BASE_CONTAINER_SCRIPT_EXHAUST_MEMORY="exhaustion-memory-engine-stressor" \
	 MEMORY_EXHAUSTION_BASE_CONTAINER_STRESS_NG_VM=1 \
	 MEMORY_EXHAUSTION_BASE_CONTAINER_STRESS_NG_VM_METHOD=write64 \
	 MEMORY_EXHAUSTION_BASE_CONTAINER_STRESS_NG_TIMEOUT=60s \
         CLEANUP=false \
	 TIMEOUT_PODMAN_STOP_CONTAINER=5 \
         NETWORK_NAME="${NETNAME}" \
         VOLUME_NAME="${VOLNAME}" \
         IMAGE_NAME_CONTAINER="quay.io/podman/stable" \
         IMAGE_COMMAND="sleep 3600" \
         NUMBER_OF_CONTAINERS="$NRM_CONTAINERS" \
         ./engine-stressor

    # podman_ps_by_name
popd 1> /dev/null || exit 1
